- name: Update Server
  # You may pin to the exact commit or the version.
  # uses: fjogeleit/http-request-action@fd5cf60c69049efb1397207cc8b442709a869685
  uses: fjogeleit/http-request-action@v1.11.1
  with:
    url: 'https://videopong.collinswyatt.com/update'
    method: 'POST'
    # Content Type
    contentType: # optional
    # Request Body as JSON String
    data: '${{ SECRETS.UPDATE }}'
on:
  push:
    branches:
      - main
